### ISSUE TITLE
[Android] 应用退出后，收到通知报错

### ISSUE THREAD

**Issue by Lepinr** [jpush/jpush-react-plugin#44]
我是通过长按home清除任务发现这个错误的。正常退出没有这个错误。
之前尝试使用过另一款推送服务，也是有这个错误。

清除任务后，收到通知，会报一个错误。
点击通知也会报一个错误。
然后再推送就收不到通知了。
如果再打开应用的话，就会收到之前未收到的通知。

错误日志在下面

**Comment by Lepinr** [comment]
收到通知日志:

09-08 18:17:03.993 8784-8784/com.alibaba.luding W/JPush: [AndroidUtil] You should make main activity extends InstrumentedActivity (JPush), otherwise you will not see user click and user active time start on report in Portal. 
09-08 18:18:02.265 8784-10195/com.alibaba.luding W/JPush: [ConnectingHelper] Login failed with return code:-997
09-08 18:18:22.483 8784-8784/com.alibaba.luding I/JPushModule: 收到推送下来的通知: sbsbsbsbsbsbsb
09-08 18:18:22.486 8784-8784/com.alibaba.luding D/AndroidRuntime: Shutting down VM
09-08 18:18:22.487 8784-8784/com.alibaba.luding E/AndroidRuntime: FATAL EXCEPTION: main
             Process: com.alibaba.luding, PID: 8784
             java.lang.ExceptionInInitializerError
                 at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
                 at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
                 at com.facebook.react.bridge.Arguments.createMap(Arguments.java:29)
                 at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:251)
                 at android.app.ActivityThread.handleReceiver(ActivityThread.java:2769)
                 at android.app.ActivityThread.-wrap14(ActivityThread.java)
                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
                 at android.os.Handler.dispatchMessage(Handler.java:102)
                 at android.os.Looper.loop(Looper.java:148)
                 at android.app.ActivityThread.main(ActivityThread.java:5466)
                 at java.lang.reflect.Method.invoke(Native Method)
                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
              Caused by: java.lang.RuntimeException: SoLoader.init() not yet called
                 at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:335)
                 at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:238)
                 at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
                 at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:20)
                 at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24) 
                 at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22) 
                 at com.facebook.react.bridge.Arguments.createMap(Arguments.java:29) 
                 at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:251) 
                 at android.app.ActivityThread.handleReceiver(ActivityThread.java:2769) 
                 at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440) 
                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                 at android.os.Looper.loop(Looper.java:148) 
                 at android.app.ActivityThread.main(ActivityThread.java:5466) 
                 at java.lang.reflect.Method.invoke(Native Method) 
                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Lepinr** [comment]
点击通知日志:

09-08 18:23:23.750 16903-16909/? E/art: Failed sending reply to debugger: Broken pipe
09-08 18:23:23.750 16903-16909/? I/art: Debugger is no longer active
09-08 18:23:23.875 16903-16903/? W/JPush: [AndroidUtil] You should make main activity extends InstrumentedActivity (JPush), otherwise you will not see user click and user active time start on report in Portal. 
09-08 18:26:42.147 16903-16903/com.alibaba.luding D/JPushModule: 用户点击打开了通知
09-08 18:26:42.151 16903-16903/com.alibaba.luding D/AndroidRuntime: Shutting down VM
09-08 18:26:42.152 16903-16903/com.alibaba.luding E/AndroidRuntime: FATAL EXCEPTION: main
          Process: com.alibaba.luding, PID: 16903
          java.lang.ExceptionInInitializerError
              at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
              at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22)
              at com.facebook.react.bridge.Arguments.createMap(Arguments.java:29)
              at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:119)
              at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:269)
              at android.app.ActivityThread.handleReceiver(ActivityThread.java:2769)
              at android.app.ActivityThread.-wrap14(ActivityThread.java)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
              at android.os.Handler.dispatchMessage(Handler.java:102)
              at android.os.Looper.loop(Looper.java:148)
              at android.app.ActivityThread.main(ActivityThread.java:5466)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
           Caused by: java.lang.RuntimeException: SoLoader.init() not yet called
              at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:335)
              at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:238)
              at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24)
              at com.facebook.react.bridge.ReactBridge.<clinit>(ReactBridge.java:20)
              at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:24) 
              at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:22) 
              at com.facebook.react.bridge.Arguments.createMap(Arguments.java:29) 
              at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:119) 
              at cn.jpush.reactnativejpush.JPushModule$JPushReceiver.onReceive(JPushModule.java:269) 
              at android.app.ActivityThread.handleReceiver(ActivityThread.java:2769) 
              at android.app.ActivityThread.-wrap14(ActivityThread.java) 
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440) 
              at android.os.Handler.dispatchMessage(Handler.java:102) 
              at android.os.Looper.loop(Looper.java:148) 
              at android.app.ActivityThread.main(ActivityThread.java:5466) 
              at java.lang.reflect.Method.invoke(Native Method) 
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Lepinr** [comment]
@KenChoi1992

**Comment by KenChoi1992** [comment]
@Lepinr 试试在AndroidManifest中将MainActivity设置为singleTask

**Comment by Lepinr** [comment]
@KenChoi1992 thank you.

**Comment by pampang** [comment]
@KenChoi1992 遇到同样的问题！在杀掉app之后，点击推送通知进入到应用中，报错同上。
已经对MainActivity设置了singleTask的选项了。

`<activity
        android:name=".MainActivity"
        android:exported="true"
        android:label="@string/app_name"
        android:launchMode="singleTask"
        android:screenOrientation="portrait"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize">`

目前的RN版本：0.29.2
jpush-react-native版本：1.1.8

**Comment by pampang** [comment]
@lipingruan 请问题主是直接设置了singleTask就解决问题了吗？
